### ISSUE TITLE
关于星云引擎国际版(MuMu Nebula)

### ISSUE THREAD

**Issue by paulzzh** [qiuyue0/Suspend-Mumu#1]
也可以在资源管理器中点暂停进程来挂起bcr进程
并且通过点击“更新PID” 程序也能正常判断进程状态
但是无法通过点击“启动”“停止”来控制进程状态(按钮只是变灰无效果)
![X~O8V9{JZP`~W}GI%@R)2DW](https://user-images.githubusercontent.com/28055560/182028919-897a407d-0379-46fe-a904-17f863af3414.png)
![8H)Y%J)5A59CDH01I8R9MS5](https://user-images.githubusercontent.com/28055560/182028938-eab3bef1-8027-40be-870d-aaae4896b094.png)
确定是用管理员权限运行的 希望能给国际版nebula做一下兼容

**Comment by qiuyue0** [comment]
模拟器的暂停/恢复是通过点击F2实现的，启动和停止按钮是用于控制加载/卸载键盘钩子。下个版本我会修改带有歧义的文本。

**Comment by paulzzh** [comment]
那是我理解错了...可以正常使用 感谢
